SET hive.exec.dynamic.partition = true;
SET hive.exec.dynamic.partition.mode = nonstrict;

DROP TABLE IF EXISTS customer;

CREATE TABLE card (
  id INT,
  timeId STRING,
  credit_card_no STRING,
  ssn INT,
  transaction_type STRING,
  transaction_value DOUBLE
)
PARTITIONED BY (branch_code INT);

INSERT INTO TABLE card 
PARTITION (branch_code)
SELECT id, timeId, credit_card_no, ssn, transaction_type, transaction_value, branch_code FROM card_external;